var GAME_LEVELS = [
  ["  x                   v  v                      v               v            x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                             o                                         <  x  ",
   "  x                                                                          x  ",
   "  x           xxxxx                                                          x  ",
   "  x                 o                  x                 p               o   x  ",
   "  x  @                                 x                                     x  ",
   "  xxxxxxxxxxx   xxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxx      xxxxxxxx  ",
   "            x   x       x   x                  x     x         x!!!!!!x         ",
   "            x!!!x       x!!!x                  x!!!!!x         x!!!!!!x         ",
   "            x!!!x       x!!!x                  x!!!!!x         x!!!!!!x         ",
   "            x!!!x       xxxxx                  xxxxxxx         xxxxxxxx         ",
   "            xxxxx                                                               ",
   "                                                                                "],
  ["                                                                                                   ",
   "                             v                   xxxxxxxxx          v             v                ",
   "         o                      v                                                                  ",
   "                                                                                                   ",
   "        xxxxxx                                                                                     ",
   "                                                          p                                        ",
   "                                         x    x                                                    ",
   " x          |                            x    x         xx                                         ",
   "                                        xx    x                                                    ",
   "        |                 o            xxx    x                           o               o    <  x",
   "                                      xxxx    x                                                    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                               xxx                                 ",
   "  @   o       o        o       o                            |  xxx                               | ",
   "                                                               xxx                                 ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                   "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x                         o                                          v          v                  x       x",
   "  x=                                                           v           xxxx                      x       x",
   "  x                       xxxxxxx         xxx                                                        x       x",
   "  x                                                                                               <  x       x",
   "  x                                                                                                  x       x",
   "  x          @                               p                                                       x       x",
   "  x                                                                                                  x       x",
   "  x  xxxxxxxxxxxxxxxxxxxxxxxxxx             xxx                                         xxxxxxx      x       x",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      x       x",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      x       x",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx            x",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx       o    x",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx            x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                  			                                                                                     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                 ",
   "                                                                                                              <  ",
   "                                                xx                                                               ",
   "                                                                                                                 ",
   "                         xx     xx    xxxxxx    xx    xx     xx   xxxxxx   xxxxx     xx                          ",
   "                         xx     xx    xx        xx    xx x   xx   xx       xx   x    xx                          ",
   "       |                 xx     xx    xxxx      xx    xx   x xx   xxxx     xx x      xx          |               ",
   "                         xx  x  xx    xx        xx    xx     xx   xx       xx   x                                ",
   "                         xxx   xxx    xxxxxx    xx    xx     xx   xxxxxx   xx    x    x                          ",
   "                                                                                                                 ",
   "             p      @                                                                      p                     ",
   "                                                                                                                 ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
